[package]
name = "system-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
itertools = "0.11.0"
serde = { version = "1.0.188", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
wasm-bindgen = "0.2.87"

[dev-dependencies]
rand = "0.8.5"
wasm-bindgen-test = "0.3.37"
serde_json = "1.0.105"
